# -*- coding: utf-8 -*-
"""pattern fatching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zeZoRao1iZ8BmVuss8FHEAYnuSTqwbSJ
"""

# from flask import Flask, request, render_template
import pandas as pd
import yfinance as yf
import warnings
import requests
from io import StringIO

# Suppress warnings
warnings.filterwarnings('ignore')
pd.options.mode.chained_assignment = None

def calculate_ema(df, period):
    """
    Calculate Exponential Moving Average (EMA) for a given period.
    Returns None if insufficient data.
    """
    if len(df) < period:
        return None
    return df['Close'].ewm(span=period, adjust=False).mean()

def poles(data):
  # Returns a list of integer indices where the close price increased by more than 7% from the previous day's close.
  final_result = []
  for i in range(1,len(data)):
    if ((data['Close'].iloc[i].item()) - data['Close'].iloc[i-1].item()) / data['Close'].iloc[i-1].item() > 0.07:
      final_result.append(i)
  return final_result

def flag(data):
  result = []
  c_poles = poles(data)
  for pole_i in c_poles:
    flag = 0
    pole_high = data['High'].iloc[pole_i].item()
    pole_low = data['Low'].iloc[pole_i].item()

    price_diff = round((pole_high - pole_low),2) #1
    pole_618 = round(pole_high - (price_diff*0.618),2) #1

    last_close = round(data['Close'].iloc[-1].item(),2)
    prev_close = round(data['Close'].iloc[-2].item(),2)

    close_diff = ((last_close - prev_close)*100/prev_close)

    if close_diff > 5 or close_diff < -5:
      continue

    if pole_i+7 >= len(data):
      continue
    else:
      for i in range(pole_i+1, pole_i+8):
        if i >= len(data):
          continue
        flag_close = data['Close'].iloc[i].item()

        flag_09ema = data['09_ema'].iloc[i]
        flag_20ema = data['20_ema'].iloc[i]

        # If EMA is NaN, it's not a valid flag condition
        if pd.isna(flag_09ema) or pd.isna(flag_20ema):
            break

        if flag_close > pole_high or flag_close < pole_618 or flag_close < flag_09ema or flag_close < flag_20ema:
          break
        else:
          flag+=1
          if flag > 6:
            result.append({
                'ticker name' : data.columns[0][1].split('.')[0],
                'start index' : data.index[pole_i].date(),
                'end index' : data.index[pole_i + flag].date(),
                'price' : data['Close'].iloc[-1].item()
            })

  return result

def index():
  all_results = []
  session = requests.Session()

  headers = {
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      "Accept-Language": "en-US,en;q=0.9",
      "Referer": "https://www.nseindia.com/"
  }

  session.get("https://www.nseindia.com", headers=headers)  # First hit homepage
  response = session.get(
      "https://nsearchives.nseindia.com/content/equities/EQUITY_L.csv",
      headers=headers
  )
  symbol_name_csv = pd.read_csv(StringIO(response.text))
  nse_stock = [symbol + '.NS' for symbol in symbol_name_csv['SYMBOL']]
  for ticker in nse_stock:
    data = yf.download(ticker, period='150d', interval='1d', progress=False) #1
    # Check if data is not empty and meets price condition
    if not data.empty and round(data['Close'].iloc[-1].item(),2) >= 100 and data['Volume'].iloc[-1].item() > 150000:
      data['09_ema'] = calculate_ema(data,9)
      data['20_ema'] = calculate_ema(data,20)
      data = data.tail(20).round(2)
      flagi = flag(data)
      df = pd.DataFrame(flagi)

      if not df.empty:
        all_results.append(df)

  # Move the return statements outside the loop
  if all_results:
    return pd.concat(all_results, ignore_index=True)
  else:
    return pd.DataFrame() # Return an empty DataFrame if no results

if __name__ == "__main__":
    stock = index()
